// <auto-generated />
using System;
using Gymify.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gymify.Services.Migrations
{
    [DbContext(typeof(GymifyDbContext))]
    [Migration("20260218014431_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoyaltyPoints");
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPointHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountPointsParticipation")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoyaltyPointHistories");
                });

            modelBuilder.Entity("Gymify.Services.Database.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpirationDate = new DateTime(2026, 3, 20, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3184),
                            MembershipId = 1,
                            PaymentDate = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(2920),
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            ExpirationDate = new DateTime(2026, 5, 19, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3453),
                            MembershipId = 2,
                            PaymentDate = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3453),
                            UserId = 12
                        },
                        new
                        {
                            Id = 3,
                            ExpirationDate = new DateTime(2026, 8, 17, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3457),
                            MembershipId = 3,
                            PaymentDate = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3457),
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            ExpirationDate = new DateTime(2027, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3459),
                            MembershipId = 4,
                            PaymentDate = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3459),
                            UserId = 14
                        },
                        new
                        {
                            Id = 5,
                            ExpirationDate = new DateTime(2026, 3, 20, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3461),
                            MembershipId = 1,
                            PaymentDate = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3460),
                            UserId = 15
                        },
                        new
                        {
                            Id = 6,
                            ExpirationDate = new DateTime(2026, 5, 19, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3462),
                            MembershipId = 2,
                            PaymentDate = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3462),
                            UserId = 16
                        },
                        new
                        {
                            Id = 7,
                            ExpirationDate = new DateTime(2026, 8, 17, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3464),
                            MembershipId = 3,
                            PaymentDate = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3464),
                            UserId = 17
                        },
                        new
                        {
                            Id = 8,
                            ExpirationDate = new DateTime(2027, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3466),
                            MembershipId = 4,
                            PaymentDate = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3465),
                            UserId = 18
                        },
                        new
                        {
                            Id = 9,
                            ExpirationDate = new DateTime(2026, 3, 20, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3467),
                            MembershipId = 1,
                            PaymentDate = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3467),
                            UserId = 19
                        },
                        new
                        {
                            Id = 10,
                            ExpirationDate = new DateTime(2026, 5, 19, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3469),
                            MembershipId = 2,
                            PaymentDate = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(3468),
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("MonthlyPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("YearPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 30.0,
                            Name = "Basic",
                            YearPrice = 300.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 45.0,
                            Name = "Standard",
                            YearPrice = 450.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 60.0,
                            Name = "Premium",
                            YearPrice = 600.0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 80.0,
                            Name = "VIP",
                            YearPrice = 800.0
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Gymify.Services.Database.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Gymify.Services.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StarNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Gymify.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 88, DateTimeKind.Utc).AddTicks(1292),
                            Description = "",
                            IsActive = true,
                            Name = "Korisnik"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 88, DateTimeKind.Utc).AddTicks(1914),
                            Description = "",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 88, DateTimeKind.Utc).AddTicks(1917),
                            Description = "",
                            IsActive = true,
                            Name = "Trener"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 88, DateTimeKind.Utc).AddTicks(1918),
                            Description = "",
                            IsActive = true,
                            Name = "Radnik"
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.SpecialOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValueOfLoyaltyPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpecialOffers");
                });

            modelBuilder.Entity("Gymify.Services.Database.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("int");

                    b.Property<int>("MaxAmountOfParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentParticipants = 10,
                            MaxAmountOfParticipants = 15,
                            Name = "HIIT",
                            StartDate = new DateTime(2026, 2, 19, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4548),
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CurrentParticipants = 12,
                            MaxAmountOfParticipants = 20,
                            Name = "Cardio Blast",
                            StartDate = new DateTime(2026, 2, 20, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4791),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CurrentParticipants = 14,
                            MaxAmountOfParticipants = 18,
                            Name = "CrossFit",
                            StartDate = new DateTime(2026, 2, 21, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4792),
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CurrentParticipants = 8,
                            MaxAmountOfParticipants = 12,
                            Name = "Yoga Flow",
                            StartDate = new DateTime(2026, 2, 22, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4805),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CurrentParticipants = 6,
                            MaxAmountOfParticipants = 10,
                            Name = "Pilates",
                            StartDate = new DateTime(2026, 2, 23, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4806),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CurrentParticipants = 11,
                            MaxAmountOfParticipants = 16,
                            Name = "Strength Training",
                            StartDate = new DateTime(2026, 2, 24, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4808),
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            CurrentParticipants = 9,
                            MaxAmountOfParticipants = 14,
                            Name = "Boxing",
                            StartDate = new DateTime(2026, 2, 25, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4809),
                            UserId = 6
                        },
                        new
                        {
                            Id = 8,
                            CurrentParticipants = 7,
                            MaxAmountOfParticipants = 15,
                            Name = "Kickboxing",
                            StartDate = new DateTime(2026, 2, 26, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4811),
                            UserId = 6
                        },
                        new
                        {
                            Id = 9,
                            CurrentParticipants = 13,
                            MaxAmountOfParticipants = 20,
                            Name = "Morning Fitness",
                            StartDate = new DateTime(2026, 2, 27, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4813),
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            CurrentParticipants = 15,
                            MaxAmountOfParticipants = 18,
                            Name = "Evening Cardio",
                            StartDate = new DateTime(2026, 2, 28, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4814),
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            CurrentParticipants = 10,
                            MaxAmountOfParticipants = 17,
                            Name = "Body Pump",
                            StartDate = new DateTime(2026, 3, 1, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4816),
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            CurrentParticipants = 8,
                            MaxAmountOfParticipants = 14,
                            Name = "Functional Training",
                            StartDate = new DateTime(2026, 3, 2, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4817),
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            CurrentParticipants = 6,
                            MaxAmountOfParticipants = 12,
                            Name = "Stretching",
                            StartDate = new DateTime(2026, 3, 3, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4819),
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CurrentParticipants = 18,
                            MaxAmountOfParticipants = 20,
                            Name = "Bootcamp",
                            StartDate = new DateTime(2026, 3, 4, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4820),
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            CurrentParticipants = 9,
                            MaxAmountOfParticipants = 15,
                            Name = "Abs Workout",
                            StartDate = new DateTime(2026, 3, 5, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4822),
                            UserId = 5
                        },
                        new
                        {
                            Id = 16,
                            CurrentParticipants = 5,
                            MaxAmountOfParticipants = 10,
                            Name = "Powerlifting",
                            StartDate = new DateTime(2026, 3, 6, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4823),
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            CurrentParticipants = 14,
                            MaxAmountOfParticipants = 20,
                            Name = "Zumba",
                            StartDate = new DateTime(2026, 3, 7, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4825),
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            CurrentParticipants = 12,
                            MaxAmountOfParticipants = 18,
                            Name = "Aerobics",
                            StartDate = new DateTime(2026, 3, 8, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4826),
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            CurrentParticipants = 11,
                            MaxAmountOfParticipants = 16,
                            Name = "Circuit Training",
                            StartDate = new DateTime(2026, 3, 9, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4828),
                            UserId = 5
                        },
                        new
                        {
                            Id = 20,
                            CurrentParticipants = 10,
                            MaxAmountOfParticipants = 15,
                            Name = "Core Workout",
                            StartDate = new DateTime(2026, 3, 10, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(4829),
                            UserId = 6
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRadnik")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTrener")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUser")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(7746),
                            Email = "ajdin@example.com",
                            FirstName = "Tarik",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Malic",
                            PasswordHash = "FXW6xdl3aaE1jYo6wCUlQIArhMdEaiTI500l8L/hwfEpmm+URvNEyWLlK7EV9xNWC4ftJW3K3Fy7VO4E+a6YmA==",
                            PasswordSalt = "ytUPqipoh2AKth+Bn1z+OkLX8og7NNI1iCiokaCHlX8aHMmcKcnPX6u4oNsSu7c3/Nca2QOK53ik74Na2pHVfaFy/Za4KGl8OHIW1R/I8qfyLz3/f6vaTZYooLdY/CKgSKb5q8ip92QbZv/cM/B5n57OUJ42+8dOW9lv0wyOmAU=",
                            Username = "tare45"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(8304),
                            Email = "amir@example.com",
                            FirstName = "Amir",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Ibrahimovic",
                            PasswordHash = "FXW6xdl3aaE1jYo6wCUlQIArhMdEaiTI500l8L/hwfEpmm+URvNEyWLlK7EV9xNWC4ftJW3K3Fy7VO4E+a6YmA==",
                            PasswordSalt = "ytUPqipoh2AKth+Bn1z+OkLX8og7NNI1iCiokaCHlX8aHMmcKcnPX6u4oNsSu7c3/Nca2QOK53ik74Na2pHVfaFy/Za4KGl8OHIW1R/I8qfyLz3/f6vaTZYooLdY/CKgSKb5q8ip92QbZv/cM/B5n57OUJ42+8dOW9lv0wyOmAU=",
                            Username = "amir56"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(8470),
                            Email = "marko@example.com",
                            FirstName = "Marko",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Markovic",
                            PasswordHash = "3Sd+eFRuhomQN9ML0N+JL1ueIkeHzqym72mdTSjYpaNfW2mMV8MTMYUnIF/cn/XOjJvPSkhb72jFxK9TR1BOcg==",
                            PasswordSalt = "jADgItgKGzShZTDJ/GibUgzsov4Q76rIFC+MGq+M91a9aXvW6cCx/UHlXLUSvGIzIYw+pEu/JFSwkKP574kaqXyGeiDeuIE6hBEig2/umm+m6KErnqgiScIJDdyB6GuDBgYl+TkNQHelOigh/NLQXdqmedAZJOrVNNSl4bZqdrU=",
                            Username = "marko78"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(8475),
                            Email = "ivan@example.com",
                            FirstName = "Ivan",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Ivic",
                            PasswordHash = "3Sd+eFRuhomQN9ML0N+JL1ueIkeHzqym72mdTSjYpaNfW2mMV8MTMYUnIF/cn/XOjJvPSkhb72jFxK9TR1BOcg==",
                            PasswordSalt = "jADgItgKGzShZTDJ/GibUgzsov4Q76rIFC+MGq+M91a9aXvW6cCx/UHlXLUSvGIzIYw+pEu/JFSwkKP574kaqXyGeiDeuIE6hBEig2/umm+m6KErnqgiScIJDdyB6GuDBgYl+TkNQHelOigh/NLQXdqmedAZJOrVNNSl4bZqdrU=",
                            Username = "ivan11"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(8660),
                            Email = "petar@example.com",
                            FirstName = "Petar",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Petrovic",
                            PasswordHash = "3Sd+eFRuhomQN9ML0N+JL1ueIkeHzqym72mdTSjYpaNfW2mMV8MTMYUnIF/cn/XOjJvPSkhb72jFxK9TR1BOcg==",
                            PasswordSalt = "jADgItgKGzShZTDJ/GibUgzsov4Q76rIFC+MGq+M91a9aXvW6cCx/UHlXLUSvGIzIYw+pEu/JFSwkKP574kaqXyGeiDeuIE6hBEig2/umm+m6KErnqgiScIJDdyB6GuDBgYl+TkNQHelOigh/NLQXdqmedAZJOrVNNSl4bZqdrU=",
                            Username = "petar21"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(8663),
                            Email = "luka@example.com",
                            FirstName = "Luka",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Lukic",
                            PasswordHash = "3Sd+eFRuhomQN9ML0N+JL1ueIkeHzqym72mdTSjYpaNfW2mMV8MTMYUnIF/cn/XOjJvPSkhb72jFxK9TR1BOcg==",
                            PasswordSalt = "jADgItgKGzShZTDJ/GibUgzsov4Q76rIFC+MGq+M91a9aXvW6cCx/UHlXLUSvGIzIYw+pEu/JFSwkKP574kaqXyGeiDeuIE6hBEig2/umm+m6KErnqgiScIJDdyB6GuDBgYl+TkNQHelOigh/NLQXdqmedAZJOrVNNSl4bZqdrU=",
                            Username = "luka34"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(8889),
                            Email = "nedim@example.com",
                            FirstName = "Nedim",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Nedimovic",
                            PasswordHash = "17QmPgtlSuQCX2ZK7f3w4ut/lS7FnQxinwAUn2j5KMlkOUmvdoXuw5UNbDZQ6OTfBvykL7XPHPCROsq7ZdRdGw==",
                            PasswordSalt = "N7rug9AQzZC3YOWtnaGP7HE2AR294lUK07ljicLU/dCIz4n6q+y2r1j8THNLVmj5UWwp6geRu81SfDRZHhpLC8EsWcTjFtv6IJq5AyyLbE3TY2A2A5w1/MdSMifln0E43NnY36CMXynJQm9RyTfLi3siIJBu0xTq5QTTRc2S6dM=",
                            Username = "nedim89"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(8894),
                            Email = "amela@example.com",
                            FirstName = "Amela",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Amelovic",
                            PasswordHash = "17QmPgtlSuQCX2ZK7f3w4ut/lS7FnQxinwAUn2j5KMlkOUmvdoXuw5UNbDZQ6OTfBvykL7XPHPCROsq7ZdRdGw==",
                            PasswordSalt = "N7rug9AQzZC3YOWtnaGP7HE2AR294lUK07ljicLU/dCIz4n6q+y2r1j8THNLVmj5UWwp6geRu81SfDRZHhpLC8EsWcTjFtv6IJq5AyyLbE3TY2A2A5w1/MdSMifln0E43NnY36CMXynJQm9RyTfLi3siIJBu0xTq5QTTRc2S6dM=",
                            Username = "amela900"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(8896),
                            Email = "tarik@example.com",
                            FirstName = "Tarik",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Tarikovic",
                            PasswordHash = "17QmPgtlSuQCX2ZK7f3w4ut/lS7FnQxinwAUn2j5KMlkOUmvdoXuw5UNbDZQ6OTfBvykL7XPHPCROsq7ZdRdGw==",
                            PasswordSalt = "N7rug9AQzZC3YOWtnaGP7HE2AR294lUK07ljicLU/dCIz4n6q+y2r1j8THNLVmj5UWwp6geRu81SfDRZHhpLC8EsWcTjFtv6IJq5AyyLbE3TY2A2A5w1/MdSMifln0E43NnY36CMXynJQm9RyTfLi3siIJBu0xTq5QTTRc2S6dM=",
                            Username = "tarik345"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(8931),
                            Email = "emina@example.com",
                            FirstName = "Emina",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Eminovic",
                            PasswordHash = "17QmPgtlSuQCX2ZK7f3w4ut/lS7FnQxinwAUn2j5KMlkOUmvdoXuw5UNbDZQ6OTfBvykL7XPHPCROsq7ZdRdGw==",
                            PasswordSalt = "N7rug9AQzZC3YOWtnaGP7HE2AR294lUK07ljicLU/dCIz4n6q+y2r1j8THNLVmj5UWwp6geRu81SfDRZHhpLC8EsWcTjFtv6IJq5AyyLbE3TY2A2A5w1/MdSMifln0E43NnY36CMXynJQm9RyTfLi3siIJBu0xTq5QTTRc2S6dM=",
                            Username = "emina112"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(9084),
                            Email = "haris1@example.com",
                            FirstName = "Haris",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Hasic",
                            PasswordHash = "0wKecZ0r2dUvMUwIDdCa7bNMxrc32W5c+eKP8h2Gto1W/quX+uuSik9D+n/MPsoL/ia1gK3n809/p2Nz6r285Q==",
                            PasswordSalt = "ikXPdW1EPI2uW+hem/RH50gKXYeixtvl2QWTBw/AuKoGeBbh+YwGknzXm8y6rILkd0WTCOz6oIT1XP1mBnyjDTggWlyraf/3eSD+bZpHc+7aYzaOCc9l0mDOuNlmDOgBBx++uImTlqJR+iRA+Lktho62QLy+xPgc8z81qzRNZLo=",
                            Username = "haris1"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(9088),
                            Email = "denis2@example.com",
                            FirstName = "Denis",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Denisovic",
                            PasswordHash = "0wKecZ0r2dUvMUwIDdCa7bNMxrc32W5c+eKP8h2Gto1W/quX+uuSik9D+n/MPsoL/ia1gK3n809/p2Nz6r285Q==",
                            PasswordSalt = "ikXPdW1EPI2uW+hem/RH50gKXYeixtvl2QWTBw/AuKoGeBbh+YwGknzXm8y6rILkd0WTCOz6oIT1XP1mBnyjDTggWlyraf/3eSD+bZpHc+7aYzaOCc9l0mDOuNlmDOgBBx++uImTlqJR+iRA+Lktho62QLy+xPgc8z81qzRNZLo=",
                            Username = "denis2"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(9091),
                            Email = "alen3@example.com",
                            FirstName = "Alen",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Alenovic",
                            PasswordHash = "0wKecZ0r2dUvMUwIDdCa7bNMxrc32W5c+eKP8h2Gto1W/quX+uuSik9D+n/MPsoL/ia1gK3n809/p2Nz6r285Q==",
                            PasswordSalt = "ikXPdW1EPI2uW+hem/RH50gKXYeixtvl2QWTBw/AuKoGeBbh+YwGknzXm8y6rILkd0WTCOz6oIT1XP1mBnyjDTggWlyraf/3eSD+bZpHc+7aYzaOCc9l0mDOuNlmDOgBBx++uImTlqJR+iRA+Lktho62QLy+xPgc8z81qzRNZLo=",
                            Username = "alen3"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(9093),
                            Email = "kenan4@example.com",
                            FirstName = "Kenan",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Kenanovic",
                            PasswordHash = "0wKecZ0r2dUvMUwIDdCa7bNMxrc32W5c+eKP8h2Gto1W/quX+uuSik9D+n/MPsoL/ia1gK3n809/p2Nz6r285Q==",
                            PasswordSalt = "ikXPdW1EPI2uW+hem/RH50gKXYeixtvl2QWTBw/AuKoGeBbh+YwGknzXm8y6rILkd0WTCOz6oIT1XP1mBnyjDTggWlyraf/3eSD+bZpHc+7aYzaOCc9l0mDOuNlmDOgBBx++uImTlqJR+iRA+Lktho62QLy+xPgc8z81qzRNZLo=",
                            Username = "kenan4"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(9111),
                            Email = "jasmin5@example.com",
                            FirstName = "Jasmin",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Jasminovic",
                            PasswordHash = "0wKecZ0r2dUvMUwIDdCa7bNMxrc32W5c+eKP8h2Gto1W/quX+uuSik9D+n/MPsoL/ia1gK3n809/p2Nz6r285Q==",
                            PasswordSalt = "ikXPdW1EPI2uW+hem/RH50gKXYeixtvl2QWTBw/AuKoGeBbh+YwGknzXm8y6rILkd0WTCOz6oIT1XP1mBnyjDTggWlyraf/3eSD+bZpHc+7aYzaOCc9l0mDOuNlmDOgBBx++uImTlqJR+iRA+Lktho62QLy+xPgc8z81qzRNZLo=",
                            Username = "jasmin5"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(9114),
                            Email = "lejla6@example.com",
                            FirstName = "Lejla",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Lejlovic",
                            PasswordHash = "0wKecZ0r2dUvMUwIDdCa7bNMxrc32W5c+eKP8h2Gto1W/quX+uuSik9D+n/MPsoL/ia1gK3n809/p2Nz6r285Q==",
                            PasswordSalt = "ikXPdW1EPI2uW+hem/RH50gKXYeixtvl2QWTBw/AuKoGeBbh+YwGknzXm8y6rILkd0WTCOz6oIT1XP1mBnyjDTggWlyraf/3eSD+bZpHc+7aYzaOCc9l0mDOuNlmDOgBBx++uImTlqJR+iRA+Lktho62QLy+xPgc8z81qzRNZLo=",
                            Username = "lejla6"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(9117),
                            Email = "sara7@example.com",
                            FirstName = "Sara",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Saric",
                            PasswordHash = "0wKecZ0r2dUvMUwIDdCa7bNMxrc32W5c+eKP8h2Gto1W/quX+uuSik9D+n/MPsoL/ia1gK3n809/p2Nz6r285Q==",
                            PasswordSalt = "ikXPdW1EPI2uW+hem/RH50gKXYeixtvl2QWTBw/AuKoGeBbh+YwGknzXm8y6rILkd0WTCOz6oIT1XP1mBnyjDTggWlyraf/3eSD+bZpHc+7aYzaOCc9l0mDOuNlmDOgBBx++uImTlqJR+iRA+Lktho62QLy+xPgc8z81qzRNZLo=",
                            Username = "sara7"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(9119),
                            Email = "amina8@example.com",
                            FirstName = "Amina",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Aminovic",
                            PasswordHash = "0wKecZ0r2dUvMUwIDdCa7bNMxrc32W5c+eKP8h2Gto1W/quX+uuSik9D+n/MPsoL/ia1gK3n809/p2Nz6r285Q==",
                            PasswordSalt = "ikXPdW1EPI2uW+hem/RH50gKXYeixtvl2QWTBw/AuKoGeBbh+YwGknzXm8y6rILkd0WTCOz6oIT1XP1mBnyjDTggWlyraf/3eSD+bZpHc+7aYzaOCc9l0mDOuNlmDOgBBx++uImTlqJR+iRA+Lktho62QLy+xPgc8z81qzRNZLo=",
                            Username = "amina8"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(9121),
                            Email = "emir9@example.com",
                            FirstName = "Emir",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Emirovic",
                            PasswordHash = "0wKecZ0r2dUvMUwIDdCa7bNMxrc32W5c+eKP8h2Gto1W/quX+uuSik9D+n/MPsoL/ia1gK3n809/p2Nz6r285Q==",
                            PasswordSalt = "ikXPdW1EPI2uW+hem/RH50gKXYeixtvl2QWTBw/AuKoGeBbh+YwGknzXm8y6rILkd0WTCOz6oIT1XP1mBnyjDTggWlyraf/3eSD+bZpHc+7aYzaOCc9l0mDOuNlmDOgBBx++uImTlqJR+iRA+Lktho62QLy+xPgc8z81qzRNZLo=",
                            Username = "emir9"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(9124),
                            Email = "nermin10@example.com",
                            FirstName = "Nermin",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Nerminovic",
                            PasswordHash = "0wKecZ0r2dUvMUwIDdCa7bNMxrc32W5c+eKP8h2Gto1W/quX+uuSik9D+n/MPsoL/ia1gK3n809/p2Nz6r285Q==",
                            PasswordSalt = "ikXPdW1EPI2uW+hem/RH50gKXYeixtvl2QWTBw/AuKoGeBbh+YwGknzXm8y6rILkd0WTCOz6oIT1XP1mBnyjDTggWlyraf/3eSD+bZpHc+7aYzaOCc9l0mDOuNlmDOgBBx++uImTlqJR+iRA+Lktho62QLy+xPgc8z81qzRNZLo=",
                            Username = "nermin10"
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAssigned = new DateTime(2026, 2, 18, 1, 44, 30, 97, DateTimeKind.Utc).AddTicks(9949),
                            RoleId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAssigned = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(594),
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAssigned = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(596),
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAssigned = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(597),
                            RoleId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateAssigned = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(598),
                            RoleId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(599),
                            RoleId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(600),
                            RoleId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateAssigned = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(600),
                            RoleId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            DateAssigned = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(601),
                            RoleId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            DateAssigned = new DateTime(2026, 2, 18, 1, 44, 30, 98, DateTimeKind.Utc).AddTicks(602),
                            RoleId = 4,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.WorkerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTaskDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExparationTaskDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkerTasks");
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPoint", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPointHistory", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Member", b =>
                {
                    b.HasOne("Gymify.Services.Database.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Payment", b =>
                {
                    b.HasOne("Gymify.Services.Database.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Reservation", b =>
                {
                    b.HasOne("Gymify.Services.Database.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Review", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Training", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.UserRole", b =>
                {
                    b.HasOne("Gymify.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Gymify.Services.Database.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
