// <auto-generated />
using System;
using Gymify.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gymify.Services.Migrations
{
    [DbContext(typeof(GymifyDbContext))]
    [Migration("20260219224226_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoyaltyPoints");
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPointHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountPointsParticipation")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoyaltyPointHistories");
                });

            modelBuilder.Entity("Gymify.Services.Database.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpirationDate = new DateTime(2026, 3, 21, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(3888),
                            MembershipId = 1,
                            PaymentDate = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(3728),
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            ExpirationDate = new DateTime(2026, 5, 20, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4103),
                            MembershipId = 2,
                            PaymentDate = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4103),
                            UserId = 12
                        },
                        new
                        {
                            Id = 3,
                            ExpirationDate = new DateTime(2026, 8, 18, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4181),
                            MembershipId = 3,
                            PaymentDate = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4181),
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            ExpirationDate = new DateTime(2027, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4183),
                            MembershipId = 4,
                            PaymentDate = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4183),
                            UserId = 14
                        },
                        new
                        {
                            Id = 5,
                            ExpirationDate = new DateTime(2026, 2, 14, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4185),
                            MembershipId = 1,
                            PaymentDate = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4184),
                            UserId = 15
                        },
                        new
                        {
                            Id = 6,
                            ExpirationDate = new DateTime(2026, 5, 20, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4186),
                            MembershipId = 2,
                            PaymentDate = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4186),
                            UserId = 16
                        },
                        new
                        {
                            Id = 7,
                            ExpirationDate = new DateTime(2026, 2, 9, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4188),
                            MembershipId = 3,
                            PaymentDate = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4188),
                            UserId = 17
                        },
                        new
                        {
                            Id = 8,
                            ExpirationDate = new DateTime(2026, 2, 14, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4190),
                            MembershipId = 4,
                            PaymentDate = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4189),
                            UserId = 18
                        },
                        new
                        {
                            Id = 9,
                            ExpirationDate = new DateTime(2026, 3, 21, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4191),
                            MembershipId = 1,
                            PaymentDate = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4191),
                            UserId = 19
                        },
                        new
                        {
                            Id = 10,
                            ExpirationDate = new DateTime(2026, 2, 9, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4193),
                            MembershipId = 2,
                            PaymentDate = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(4192),
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("MonthlyPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("YearPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 30.0,
                            Name = "Basic",
                            YearPrice = 300.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 45.0,
                            Name = "Standard",
                            YearPrice = 450.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 60.0,
                            Name = "Premium",
                            YearPrice = 600.0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 80.0,
                            Name = "VIP",
                            YearPrice = 800.0
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Funkcionalni trening planiran za večeras je otkazan.",
                            CreatedAt = new DateTime(2026, 2, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Termini pilatesa za sljedeću sedmicu su Uto-Sri-Pet 17:00.",
                            CreatedAt = new DateTime(2026, 2, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Podsjetnik: članarine se mogu produžiti do 25. u mjesecu.",
                            CreatedAt = new DateTime(2026, 2, 14, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 7
                        },
                        new
                        {
                            Id = 4,
                            Content = "U subotu radimo skraćeno: 09:00–14:00.",
                            CreatedAt = new DateTime(2026, 2, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 8
                        },
                        new
                        {
                            Id = 5,
                            Content = "Uveden je novi VIP paket članarine. Pogledajte detalje na recepciji.",
                            CreatedAt = new DateTime(2026, 2, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Molimo članove da nakon treninga vraćaju opremu na mjesto.",
                            CreatedAt = new DateTime(2026, 2, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 9
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Gymify.Services.Database.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Gymify.Services.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StarNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "Odlična teretana, čisto i uredno. Preporuka!",
                            StarNumber = 5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            Message = "Treninzi su super, ali bi volio više večernjih termina.",
                            StarNumber = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 3,
                            Message = "Osoblje je ljubazno i uvijek spremno pomoći.",
                            StarNumber = 5,
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            Message = "Dobra oprema, ponekad gužva u špici.",
                            StarNumber = 4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 5,
                            Message = "Zadovoljan sam. Treneri su stvarno profesionalni.",
                            StarNumber = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 6,
                            Message = "Sve je top, jedino bi muzika mogla biti malo tiša.",
                            StarNumber = 4,
                            UserId = 16
                        },
                        new
                        {
                            Id = 7,
                            Message = "Najbolja teretana u gradu!",
                            StarNumber = 5,
                            UserId = 17
                        },
                        new
                        {
                            Id = 8,
                            Message = "Sviđa mi se što je uvijek čisto i uredno.",
                            StarNumber = 5,
                            UserId = 18
                        },
                        new
                        {
                            Id = 9,
                            Message = "Dobro iskustvo, ali bih volio više sprava za noge.",
                            StarNumber = 4,
                            UserId = 19
                        },
                        new
                        {
                            Id = 10,
                            Message = "Super atmosfera i odlična organizacija.",
                            StarNumber = 5,
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 640, DateTimeKind.Utc).AddTicks(8021),
                            Description = "",
                            IsActive = true,
                            Name = "Korisnik"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 640, DateTimeKind.Utc).AddTicks(8770),
                            Description = "",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 640, DateTimeKind.Utc).AddTicks(8773),
                            Description = "",
                            IsActive = true,
                            Name = "Trener"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 640, DateTimeKind.Utc).AddTicks(8774),
                            Description = "",
                            IsActive = true,
                            Name = "Radnik"
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.SpecialOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValueOfLoyaltyPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpecialOffers");
                });

            modelBuilder.Entity("Gymify.Services.Database.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("int");

                    b.Property<int>("MaxAmountOfParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainingImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentParticipants = 10,
                            MaxAmountOfParticipants = 15,
                            Name = "HIIT",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/hiit/600/400",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CurrentParticipants = 12,
                            MaxAmountOfParticipants = 20,
                            Name = "Cardio Blast",
                            StartDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/cardioblast/600/400",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CurrentParticipants = 14,
                            MaxAmountOfParticipants = 18,
                            Name = "CrossFit",
                            StartDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/crossfit/600/400",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CurrentParticipants = 8,
                            MaxAmountOfParticipants = 12,
                            Name = "Yoga Flow",
                            StartDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/yogaflow/600/400",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CurrentParticipants = 6,
                            MaxAmountOfParticipants = 10,
                            Name = "Pilates",
                            StartDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/pilates/600/400",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CurrentParticipants = 11,
                            MaxAmountOfParticipants = 16,
                            Name = "Strength Training",
                            StartDate = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/strength/600/400",
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            CurrentParticipants = 9,
                            MaxAmountOfParticipants = 14,
                            Name = "Boxing",
                            StartDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/boxing/600/400",
                            UserId = 6
                        },
                        new
                        {
                            Id = 8,
                            CurrentParticipants = 7,
                            MaxAmountOfParticipants = 15,
                            Name = "Kickboxing",
                            StartDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/kickboxing/600/400",
                            UserId = 6
                        },
                        new
                        {
                            Id = 9,
                            CurrentParticipants = 13,
                            MaxAmountOfParticipants = 20,
                            Name = "Morning Fitness",
                            StartDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/morningfitness/600/400",
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            CurrentParticipants = 15,
                            MaxAmountOfParticipants = 18,
                            Name = "Evening Cardio",
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/eveningcardio/600/400",
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            CurrentParticipants = 10,
                            MaxAmountOfParticipants = 17,
                            Name = "Body Pump",
                            StartDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/bodypump/600/400",
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            CurrentParticipants = 8,
                            MaxAmountOfParticipants = 14,
                            Name = "Functional Training",
                            StartDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/functional/600/400",
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            CurrentParticipants = 6,
                            MaxAmountOfParticipants = 12,
                            Name = "Stretching",
                            StartDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/stretching/600/400",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CurrentParticipants = 18,
                            MaxAmountOfParticipants = 20,
                            Name = "Bootcamp",
                            StartDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/bootcamp/600/400",
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            CurrentParticipants = 9,
                            MaxAmountOfParticipants = 15,
                            Name = "Abs Workout",
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/absworkout/600/400",
                            UserId = 5
                        },
                        new
                        {
                            Id = 16,
                            CurrentParticipants = 5,
                            MaxAmountOfParticipants = 10,
                            Name = "Powerlifting",
                            StartDate = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/powerlifting/600/400",
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            CurrentParticipants = 14,
                            MaxAmountOfParticipants = 20,
                            Name = "Zumba",
                            StartDate = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/zumba/600/400",
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            CurrentParticipants = 12,
                            MaxAmountOfParticipants = 18,
                            Name = "Aerobics",
                            StartDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/aerobics/600/400",
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            CurrentParticipants = 11,
                            MaxAmountOfParticipants = 16,
                            Name = "Circuit Training",
                            StartDate = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/circuit/600/400",
                            UserId = 5
                        },
                        new
                        {
                            Id = 20,
                            CurrentParticipants = 10,
                            MaxAmountOfParticipants = 15,
                            Name = "Core Workout",
                            StartDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/core/600/400",
                            UserId = 6
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRadnik")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTrener")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUser")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(8793),
                            Email = "ajdin@example.com",
                            FirstName = "Tarik",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Malic",
                            PasswordHash = "gZG89uoAWnr/1a7xS/dum0tZwgRGuhgDMrcfmykmHsEReTWmhlwq8dk5EIlzrfFEYpjNBOAPdyjXWFTkNYItug==",
                            PasswordSalt = "yOUA8Z6giV5/rz2M2V3TQcd1CULqSglnNG0B9ZVs8ZQUTDijSKJyYM7dHfithv1pGtyfahqOc+feFiCokr0dH3g0U/cIEjqHrBPIVQNzAWAcXKKyzpzfEesWoKvgoRbpzldgDGg95R3xJqVkmsQNLIZ1kJVo+HWzLYMu3PIcOzk=",
                            Username = "tare45"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9287),
                            Email = "amir@example.com",
                            FirstName = "Amir",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Ibrahimovic",
                            PasswordHash = "gZG89uoAWnr/1a7xS/dum0tZwgRGuhgDMrcfmykmHsEReTWmhlwq8dk5EIlzrfFEYpjNBOAPdyjXWFTkNYItug==",
                            PasswordSalt = "yOUA8Z6giV5/rz2M2V3TQcd1CULqSglnNG0B9ZVs8ZQUTDijSKJyYM7dHfithv1pGtyfahqOc+feFiCokr0dH3g0U/cIEjqHrBPIVQNzAWAcXKKyzpzfEesWoKvgoRbpzldgDGg95R3xJqVkmsQNLIZ1kJVo+HWzLYMu3PIcOzk=",
                            Username = "amir56"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9442),
                            Email = "marko@example.com",
                            FirstName = "Marko",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Markovic",
                            PasswordHash = "TU72NqxpEJsSbhpOaYhTJ511zkrVtIq1qJZvl4GY8eNNLS6Zn4zpN78jgq/BId4l+IGl4DnyDTWxMqdPIvya/Q==",
                            PasswordSalt = "mK/PFxjiPuWXf7FrUhbwK8UCb7cP6UaruPYcqjJvhXOHTYHUBM26O0s3Mebt7cfYw3R6gppIn7ZrI95lIYYoXjVmmsb3ParPb/MXCzh4gIE4W/rIVBxizwy5MWYmQZOPJqdM1DZXDqEowut1Yz4uDppGwAMoaiRLw2FSjy4v+6Y=",
                            Username = "marko78"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9447),
                            Email = "ivan@example.com",
                            FirstName = "Ivan",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Ivic",
                            PasswordHash = "TU72NqxpEJsSbhpOaYhTJ511zkrVtIq1qJZvl4GY8eNNLS6Zn4zpN78jgq/BId4l+IGl4DnyDTWxMqdPIvya/Q==",
                            PasswordSalt = "mK/PFxjiPuWXf7FrUhbwK8UCb7cP6UaruPYcqjJvhXOHTYHUBM26O0s3Mebt7cfYw3R6gppIn7ZrI95lIYYoXjVmmsb3ParPb/MXCzh4gIE4W/rIVBxizwy5MWYmQZOPJqdM1DZXDqEowut1Yz4uDppGwAMoaiRLw2FSjy4v+6Y=",
                            Username = "ivan11"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9470),
                            Email = "petar@example.com",
                            FirstName = "Petar",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Petrovic",
                            PasswordHash = "TU72NqxpEJsSbhpOaYhTJ511zkrVtIq1qJZvl4GY8eNNLS6Zn4zpN78jgq/BId4l+IGl4DnyDTWxMqdPIvya/Q==",
                            PasswordSalt = "mK/PFxjiPuWXf7FrUhbwK8UCb7cP6UaruPYcqjJvhXOHTYHUBM26O0s3Mebt7cfYw3R6gppIn7ZrI95lIYYoXjVmmsb3ParPb/MXCzh4gIE4W/rIVBxizwy5MWYmQZOPJqdM1DZXDqEowut1Yz4uDppGwAMoaiRLw2FSjy4v+6Y=",
                            Username = "petar21"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9472),
                            Email = "luka@example.com",
                            FirstName = "Luka",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Lukic",
                            PasswordHash = "TU72NqxpEJsSbhpOaYhTJ511zkrVtIq1qJZvl4GY8eNNLS6Zn4zpN78jgq/BId4l+IGl4DnyDTWxMqdPIvya/Q==",
                            PasswordSalt = "mK/PFxjiPuWXf7FrUhbwK8UCb7cP6UaruPYcqjJvhXOHTYHUBM26O0s3Mebt7cfYw3R6gppIn7ZrI95lIYYoXjVmmsb3ParPb/MXCzh4gIE4W/rIVBxizwy5MWYmQZOPJqdM1DZXDqEowut1Yz4uDppGwAMoaiRLw2FSjy4v+6Y=",
                            Username = "luka34"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9633),
                            Email = "nedim@example.com",
                            FirstName = "Nedim",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Nedimovic",
                            PasswordHash = "biIYFFUPr+7Wo5ooUQ44ip8Xr2Z3Y+++bNsYeTQZxL7cJ/mKnJn0bNBp1sv1BwiXk2RYmOLohs2/LlOTAc+/SQ==",
                            PasswordSalt = "ikLR2zFl8PwR+1c7OIiy2Zgvv9/reDnGYa5/otiNt6WQHAmXzFURPXQJZBV7Ckq+FBerCSk7kXAKZ+SjuuIFzCAuEXk3cl6iYjPR3Jh2NAWbZnk4OIJ2aYraO42A2OMbFQpnzUqRvbDvYgIZYabqi0+WwNTAFEmaovqcK+eOfsI=",
                            Username = "nedim89"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9637),
                            Email = "amela@example.com",
                            FirstName = "Amela",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Amelovic",
                            PasswordHash = "biIYFFUPr+7Wo5ooUQ44ip8Xr2Z3Y+++bNsYeTQZxL7cJ/mKnJn0bNBp1sv1BwiXk2RYmOLohs2/LlOTAc+/SQ==",
                            PasswordSalt = "ikLR2zFl8PwR+1c7OIiy2Zgvv9/reDnGYa5/otiNt6WQHAmXzFURPXQJZBV7Ckq+FBerCSk7kXAKZ+SjuuIFzCAuEXk3cl6iYjPR3Jh2NAWbZnk4OIJ2aYraO42A2OMbFQpnzUqRvbDvYgIZYabqi0+WwNTAFEmaovqcK+eOfsI=",
                            Username = "amela900"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9639),
                            Email = "tarik@example.com",
                            FirstName = "Tarik",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Tarikovic",
                            PasswordHash = "biIYFFUPr+7Wo5ooUQ44ip8Xr2Z3Y+++bNsYeTQZxL7cJ/mKnJn0bNBp1sv1BwiXk2RYmOLohs2/LlOTAc+/SQ==",
                            PasswordSalt = "ikLR2zFl8PwR+1c7OIiy2Zgvv9/reDnGYa5/otiNt6WQHAmXzFURPXQJZBV7Ckq+FBerCSk7kXAKZ+SjuuIFzCAuEXk3cl6iYjPR3Jh2NAWbZnk4OIJ2aYraO42A2OMbFQpnzUqRvbDvYgIZYabqi0+WwNTAFEmaovqcK+eOfsI=",
                            Username = "tarik345"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9642),
                            Email = "emina@example.com",
                            FirstName = "Emina",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Eminovic",
                            PasswordHash = "biIYFFUPr+7Wo5ooUQ44ip8Xr2Z3Y+++bNsYeTQZxL7cJ/mKnJn0bNBp1sv1BwiXk2RYmOLohs2/LlOTAc+/SQ==",
                            PasswordSalt = "ikLR2zFl8PwR+1c7OIiy2Zgvv9/reDnGYa5/otiNt6WQHAmXzFURPXQJZBV7Ckq+FBerCSk7kXAKZ+SjuuIFzCAuEXk3cl6iYjPR3Jh2NAWbZnk4OIJ2aYraO42A2OMbFQpnzUqRvbDvYgIZYabqi0+WwNTAFEmaovqcK+eOfsI=",
                            Username = "emina112"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9790),
                            Email = "haris1@example.com",
                            FirstName = "Haris",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Hasic",
                            PasswordHash = "t9ZbmKS3vavfM5KUYLtHGv2S8dnFY3O/+/L5tqS/P7Y4OoAdOH+7zcv4IBoSNXi8v4xLNegi2qlVQUhzfYO7fg==",
                            PasswordSalt = "Lw2d/jLp/lCTRyfpn3cNg2N9L1x2yuhAZV2KIjbZYz4+CnyVQ332tvibEZhSRffWz7eDv4oqpgJ8PvoQbGFrboO36HBha6Jz0CF4uuSmWolYOz6T71dgljk0e8jtEpPPnbmFYBm5Cn8ljFjKBE/yVkkFAAAGnrLt2JSTgog+qzI=",
                            Username = "haris1"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9794),
                            Email = "denis2@example.com",
                            FirstName = "Denis",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Denisovic",
                            PasswordHash = "t9ZbmKS3vavfM5KUYLtHGv2S8dnFY3O/+/L5tqS/P7Y4OoAdOH+7zcv4IBoSNXi8v4xLNegi2qlVQUhzfYO7fg==",
                            PasswordSalt = "Lw2d/jLp/lCTRyfpn3cNg2N9L1x2yuhAZV2KIjbZYz4+CnyVQ332tvibEZhSRffWz7eDv4oqpgJ8PvoQbGFrboO36HBha6Jz0CF4uuSmWolYOz6T71dgljk0e8jtEpPPnbmFYBm5Cn8ljFjKBE/yVkkFAAAGnrLt2JSTgog+qzI=",
                            Username = "denis2"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9796),
                            Email = "alen3@example.com",
                            FirstName = "Alen",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Alenovic",
                            PasswordHash = "t9ZbmKS3vavfM5KUYLtHGv2S8dnFY3O/+/L5tqS/P7Y4OoAdOH+7zcv4IBoSNXi8v4xLNegi2qlVQUhzfYO7fg==",
                            PasswordSalt = "Lw2d/jLp/lCTRyfpn3cNg2N9L1x2yuhAZV2KIjbZYz4+CnyVQ332tvibEZhSRffWz7eDv4oqpgJ8PvoQbGFrboO36HBha6Jz0CF4uuSmWolYOz6T71dgljk0e8jtEpPPnbmFYBm5Cn8ljFjKBE/yVkkFAAAGnrLt2JSTgog+qzI=",
                            Username = "alen3"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9799),
                            Email = "kenan4@example.com",
                            FirstName = "Kenan",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Kenanovic",
                            PasswordHash = "t9ZbmKS3vavfM5KUYLtHGv2S8dnFY3O/+/L5tqS/P7Y4OoAdOH+7zcv4IBoSNXi8v4xLNegi2qlVQUhzfYO7fg==",
                            PasswordSalt = "Lw2d/jLp/lCTRyfpn3cNg2N9L1x2yuhAZV2KIjbZYz4+CnyVQ332tvibEZhSRffWz7eDv4oqpgJ8PvoQbGFrboO36HBha6Jz0CF4uuSmWolYOz6T71dgljk0e8jtEpPPnbmFYBm5Cn8ljFjKBE/yVkkFAAAGnrLt2JSTgog+qzI=",
                            Username = "kenan4"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9817),
                            Email = "jasmin5@example.com",
                            FirstName = "Jasmin",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Jasminovic",
                            PasswordHash = "t9ZbmKS3vavfM5KUYLtHGv2S8dnFY3O/+/L5tqS/P7Y4OoAdOH+7zcv4IBoSNXi8v4xLNegi2qlVQUhzfYO7fg==",
                            PasswordSalt = "Lw2d/jLp/lCTRyfpn3cNg2N9L1x2yuhAZV2KIjbZYz4+CnyVQ332tvibEZhSRffWz7eDv4oqpgJ8PvoQbGFrboO36HBha6Jz0CF4uuSmWolYOz6T71dgljk0e8jtEpPPnbmFYBm5Cn8ljFjKBE/yVkkFAAAGnrLt2JSTgog+qzI=",
                            Username = "jasmin5"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9820),
                            Email = "lejla6@example.com",
                            FirstName = "Lejla",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Lejlovic",
                            PasswordHash = "t9ZbmKS3vavfM5KUYLtHGv2S8dnFY3O/+/L5tqS/P7Y4OoAdOH+7zcv4IBoSNXi8v4xLNegi2qlVQUhzfYO7fg==",
                            PasswordSalt = "Lw2d/jLp/lCTRyfpn3cNg2N9L1x2yuhAZV2KIjbZYz4+CnyVQ332tvibEZhSRffWz7eDv4oqpgJ8PvoQbGFrboO36HBha6Jz0CF4uuSmWolYOz6T71dgljk0e8jtEpPPnbmFYBm5Cn8ljFjKBE/yVkkFAAAGnrLt2JSTgog+qzI=",
                            Username = "lejla6"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9822),
                            Email = "sara7@example.com",
                            FirstName = "Sara",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Saric",
                            PasswordHash = "t9ZbmKS3vavfM5KUYLtHGv2S8dnFY3O/+/L5tqS/P7Y4OoAdOH+7zcv4IBoSNXi8v4xLNegi2qlVQUhzfYO7fg==",
                            PasswordSalt = "Lw2d/jLp/lCTRyfpn3cNg2N9L1x2yuhAZV2KIjbZYz4+CnyVQ332tvibEZhSRffWz7eDv4oqpgJ8PvoQbGFrboO36HBha6Jz0CF4uuSmWolYOz6T71dgljk0e8jtEpPPnbmFYBm5Cn8ljFjKBE/yVkkFAAAGnrLt2JSTgog+qzI=",
                            Username = "sara7"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9824),
                            Email = "amina8@example.com",
                            FirstName = "Amina",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Aminovic",
                            PasswordHash = "t9ZbmKS3vavfM5KUYLtHGv2S8dnFY3O/+/L5tqS/P7Y4OoAdOH+7zcv4IBoSNXi8v4xLNegi2qlVQUhzfYO7fg==",
                            PasswordSalt = "Lw2d/jLp/lCTRyfpn3cNg2N9L1x2yuhAZV2KIjbZYz4+CnyVQ332tvibEZhSRffWz7eDv4oqpgJ8PvoQbGFrboO36HBha6Jz0CF4uuSmWolYOz6T71dgljk0e8jtEpPPnbmFYBm5Cn8ljFjKBE/yVkkFAAAGnrLt2JSTgog+qzI=",
                            Username = "amina8"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9827),
                            Email = "emir9@example.com",
                            FirstName = "Emir",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Emirovic",
                            PasswordHash = "t9ZbmKS3vavfM5KUYLtHGv2S8dnFY3O/+/L5tqS/P7Y4OoAdOH+7zcv4IBoSNXi8v4xLNegi2qlVQUhzfYO7fg==",
                            PasswordSalt = "Lw2d/jLp/lCTRyfpn3cNg2N9L1x2yuhAZV2KIjbZYz4+CnyVQ332tvibEZhSRffWz7eDv4oqpgJ8PvoQbGFrboO36HBha6Jz0CF4uuSmWolYOz6T71dgljk0e8jtEpPPnbmFYBm5Cn8ljFjKBE/yVkkFAAAGnrLt2JSTgog+qzI=",
                            Username = "emir9"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 2, 19, 22, 42, 25, 648, DateTimeKind.Utc).AddTicks(9830),
                            Email = "nermin10@example.com",
                            FirstName = "Nermin",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Nerminovic",
                            PasswordHash = "t9ZbmKS3vavfM5KUYLtHGv2S8dnFY3O/+/L5tqS/P7Y4OoAdOH+7zcv4IBoSNXi8v4xLNegi2qlVQUhzfYO7fg==",
                            PasswordSalt = "Lw2d/jLp/lCTRyfpn3cNg2N9L1x2yuhAZV2KIjbZYz4+CnyVQ332tvibEZhSRffWz7eDv4oqpgJ8PvoQbGFrboO36HBha6Jz0CF4uuSmWolYOz6T71dgljk0e8jtEpPPnbmFYBm5Cn8ljFjKBE/yVkkFAAAGnrLt2JSTgog+qzI=",
                            Username = "nermin10"
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAssigned = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(668),
                            RoleId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAssigned = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(1136),
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAssigned = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(1137),
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAssigned = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(1138),
                            RoleId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateAssigned = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(1139),
                            RoleId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(1140),
                            RoleId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(1140),
                            RoleId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateAssigned = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(1141),
                            RoleId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            DateAssigned = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(1142),
                            RoleId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            DateAssigned = new DateTime(2026, 2, 19, 22, 42, 25, 649, DateTimeKind.Utc).AddTicks(1143),
                            RoleId = 4,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.WorkerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTaskDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExparationTaskDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkerTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTaskDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Izvršiti dnevnu provjeru sprava u sali 1.",
                            ExparationTaskDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = false,
                            Name = "Provjera opreme",
                            UserId = 7
                        },
                        new
                        {
                            Id = 2,
                            CreatedTaskDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Detaljno čišćenje muške svlačionice.",
                            ExparationTaskDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = true,
                            Name = "Čišćenje svlačionice",
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            CreatedTaskDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Provjeriti stanje proteinskih napitaka.",
                            ExparationTaskDate = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = false,
                            Name = "Inventura šanka",
                            UserId = 8
                        },
                        new
                        {
                            Id = 4,
                            CreatedTaskDate = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Rasporediti termine za nove članove.",
                            ExparationTaskDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = false,
                            Name = "Organizacija termina",
                            UserId = 8
                        },
                        new
                        {
                            Id = 5,
                            CreatedTaskDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Provjeriti članarine koje ističu ove sedmice.",
                            ExparationTaskDate = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = true,
                            Name = "Ažuriranje članova",
                            UserId = 9
                        },
                        new
                        {
                            Id = 6,
                            CreatedTaskDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Pripremiti salu za večernji grupni trening.",
                            ExparationTaskDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = false,
                            Name = "Priprema sale",
                            UserId = 9
                        },
                        new
                        {
                            Id = 7,
                            CreatedTaskDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Objaviti promociju na društvenim mrežama.",
                            ExparationTaskDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = false,
                            Name = "Marketing objava",
                            UserId = 10
                        },
                        new
                        {
                            Id = 8,
                            CreatedTaskDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Provjeriti rezervacije za vikend termine.",
                            ExparationTaskDate = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = true,
                            Name = "Pregled rezervacija",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPoint", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPointHistory", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Member", b =>
                {
                    b.HasOne("Gymify.Services.Database.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Notification", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Payment", b =>
                {
                    b.HasOne("Gymify.Services.Database.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Reservation", b =>
                {
                    b.HasOne("Gymify.Services.Database.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Review", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Training", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.UserRole", b =>
                {
                    b.HasOne("Gymify.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.WorkerTask", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Gymify.Services.Database.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
