// <auto-generated />
using System;
using Gymify.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gymify.Services.Migrations
{
    [DbContext(typeof(GymifyDbContext))]
    [Migration("20260303035746_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoyaltyPoints");
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPointHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountPointsParticipation")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoyaltyPointHistories");
                });

            modelBuilder.Entity("Gymify.Services.Database.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpirationDate = new DateTime(2026, 2, 28, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1062),
                            MembershipId = 2,
                            PaymentDate = new DateTime(2026, 3, 3, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(900),
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            ExpirationDate = new DateTime(2026, 6, 1, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1318),
                            MembershipId = 2,
                            PaymentDate = new DateTime(2026, 3, 3, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1318),
                            UserId = 12
                        },
                        new
                        {
                            Id = 3,
                            ExpirationDate = new DateTime(2026, 8, 30, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1323),
                            MembershipId = 3,
                            PaymentDate = new DateTime(2026, 3, 3, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1322),
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            ExpirationDate = new DateTime(2027, 3, 3, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1324),
                            MembershipId = 4,
                            PaymentDate = new DateTime(2026, 3, 3, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1324),
                            UserId = 14
                        },
                        new
                        {
                            Id = 5,
                            ExpirationDate = new DateTime(2026, 2, 26, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1326),
                            MembershipId = 1,
                            PaymentDate = new DateTime(2026, 3, 3, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1326),
                            UserId = 15
                        },
                        new
                        {
                            Id = 6,
                            ExpirationDate = new DateTime(2026, 6, 1, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1327),
                            MembershipId = 2,
                            PaymentDate = new DateTime(2026, 3, 3, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1327),
                            UserId = 16
                        },
                        new
                        {
                            Id = 7,
                            ExpirationDate = new DateTime(2026, 2, 21, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1350),
                            MembershipId = 3,
                            PaymentDate = new DateTime(2026, 3, 3, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1350),
                            UserId = 17
                        },
                        new
                        {
                            Id = 8,
                            ExpirationDate = new DateTime(2026, 2, 26, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1351),
                            MembershipId = 4,
                            PaymentDate = new DateTime(2026, 3, 3, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1351),
                            UserId = 18
                        },
                        new
                        {
                            Id = 9,
                            ExpirationDate = new DateTime(2026, 4, 2, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1353),
                            MembershipId = 1,
                            PaymentDate = new DateTime(2026, 3, 3, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1352),
                            UserId = 19
                        },
                        new
                        {
                            Id = 10,
                            ExpirationDate = new DateTime(2026, 2, 21, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1354),
                            MembershipId = 2,
                            PaymentDate = new DateTime(2026, 3, 3, 3, 57, 46, 414, DateTimeKind.Utc).AddTicks(1354),
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("MonthlyPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("YearPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 30.0,
                            Name = "Basic",
                            YearPrice = 300.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 45.0,
                            Name = "Standard",
                            YearPrice = 450.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 60.0,
                            Name = "Premium",
                            YearPrice = 600.0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyPrice = 80.0,
                            Name = "VIP",
                            YearPrice = 800.0
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Funkcionalni trening planiran za večeras je otkazan.",
                            CreatedAt = new DateTime(2026, 2, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Termini pilatesa za sljedeću sedmicu su Uto-Sri-Pet 17:00.",
                            CreatedAt = new DateTime(2026, 2, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Podsjetnik: članarine se mogu produžiti do 25. u mjesecu.",
                            CreatedAt = new DateTime(2026, 2, 14, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 7
                        },
                        new
                        {
                            Id = 4,
                            Content = "U subotu radimo skraćeno: 09:00–14:00.",
                            CreatedAt = new DateTime(2026, 2, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 8
                        },
                        new
                        {
                            Id = 5,
                            Content = "Uveden je novi VIP paket članarine. Pogledajte detalje na recepciji.",
                            CreatedAt = new DateTime(2026, 2, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Molimo članove da nakon treninga vraćaju opremu na mjesto.",
                            CreatedAt = new DateTime(2026, 2, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Obavijest",
                            UserId = 9
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 45.0,
                            MembershipId = 2,
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = "Paid",
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            Amount = 45.0,
                            MembershipId = 2,
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = "Paid",
                            UserId = 12
                        },
                        new
                        {
                            Id = 3,
                            Amount = 60.0,
                            MembershipId = 3,
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = "Paid",
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            Amount = 80.0,
                            MembershipId = 4,
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = "Paid",
                            UserId = 14
                        },
                        new
                        {
                            Id = 5,
                            Amount = 30.0,
                            MembershipId = 1,
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = "Paid",
                            UserId = 15
                        },
                        new
                        {
                            Id = 6,
                            Amount = 45.0,
                            MembershipId = 2,
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = "Paid",
                            UserId = 16
                        },
                        new
                        {
                            Id = 7,
                            Amount = 60.0,
                            MembershipId = 3,
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = "Paid",
                            UserId = 17
                        },
                        new
                        {
                            Id = 8,
                            Amount = 80.0,
                            MembershipId = 4,
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = "Paid",
                            UserId = 18
                        },
                        new
                        {
                            Id = 9,
                            Amount = 30.0,
                            MembershipId = 1,
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = "Paid",
                            UserId = 19
                        },
                        new
                        {
                            Id = 10,
                            Amount = 45.0,
                            MembershipId = 2,
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentStatus = "Paid",
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            TrainingId = 21,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingId = 22,
                            UserId = 11
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 19, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            TrainingId = 23,
                            UserId = 11
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 24, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            TrainingId = 24,
                            UserId = 11
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StarNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "Odlična teretana, čisto i uredno. Preporuka!",
                            StarNumber = 5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            Message = "Treninzi su super, ali bi volio više večernjih termina.",
                            StarNumber = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 3,
                            Message = "Osoblje je ljubazno i uvijek spremno pomoći.",
                            StarNumber = 5,
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            Message = "Dobra oprema, ponekad gužva u špici.",
                            StarNumber = 4,
                            UserId = 14
                        },
                        new
                        {
                            Id = 5,
                            Message = "Zadovoljan sam. Treneri su stvarno profesionalni.",
                            StarNumber = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 6,
                            Message = "Sve je top, jedino bi muzika mogla biti malo tiša.",
                            StarNumber = 4,
                            UserId = 16
                        },
                        new
                        {
                            Id = 7,
                            Message = "Najbolja teretana u gradu!",
                            StarNumber = 5,
                            UserId = 17
                        },
                        new
                        {
                            Id = 8,
                            Message = "Sviđa mi se što je uvijek čisto i uredno.",
                            StarNumber = 5,
                            UserId = 18
                        },
                        new
                        {
                            Id = 9,
                            Message = "Dobro iskustvo, ali bih volio više sprava za noge.",
                            StarNumber = 4,
                            UserId = 19
                        },
                        new
                        {
                            Id = 10,
                            Message = "Super atmosfera i odlična organizacija.",
                            StarNumber = 5,
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 3, 3, 57, 46, 407, DateTimeKind.Utc).AddTicks(8442),
                            Description = "",
                            IsActive = true,
                            Name = "Korisnik"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 3, 3, 57, 46, 407, DateTimeKind.Utc).AddTicks(8855),
                            Description = "",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 3, 3, 57, 46, 407, DateTimeKind.Utc).AddTicks(8857),
                            Description = "",
                            IsActive = true,
                            Name = "Trener"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 3, 3, 57, 46, 407, DateTimeKind.Utc).AddTicks(8858),
                            Description = "",
                            IsActive = true,
                            Name = "Radnik"
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.SpecialOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValueOfLoyaltyPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpecialOffers");
                });

            modelBuilder.Entity("Gymify.Services.Database.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("int");

                    b.Property<int>("MaxAmountOfParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainingImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentParticipants = 10,
                            MaxAmountOfParticipants = 15,
                            Name = "HIIT",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/hiit/600/400",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CurrentParticipants = 12,
                            MaxAmountOfParticipants = 20,
                            Name = "Cardio Blast",
                            StartDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/cardioblast/600/400",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CurrentParticipants = 14,
                            MaxAmountOfParticipants = 18,
                            Name = "CrossFit",
                            StartDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/crossfit/600/400",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CurrentParticipants = 8,
                            MaxAmountOfParticipants = 12,
                            Name = "Yoga Flow",
                            StartDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/yogaflow/600/400",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CurrentParticipants = 6,
                            MaxAmountOfParticipants = 10,
                            Name = "Pilates",
                            StartDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/pilates/600/400",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CurrentParticipants = 11,
                            MaxAmountOfParticipants = 16,
                            Name = "Strength Training",
                            StartDate = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/strength/600/400",
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            CurrentParticipants = 9,
                            MaxAmountOfParticipants = 14,
                            Name = "Boxing",
                            StartDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/boxing/600/400",
                            UserId = 6
                        },
                        new
                        {
                            Id = 8,
                            CurrentParticipants = 7,
                            MaxAmountOfParticipants = 15,
                            Name = "Kickboxing",
                            StartDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/kickboxing/600/400",
                            UserId = 6
                        },
                        new
                        {
                            Id = 9,
                            CurrentParticipants = 13,
                            MaxAmountOfParticipants = 20,
                            Name = "Morning Fitness",
                            StartDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/morningfitness/600/400",
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            CurrentParticipants = 15,
                            MaxAmountOfParticipants = 18,
                            Name = "Evening Cardio",
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/eveningcardio/600/400",
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            CurrentParticipants = 10,
                            MaxAmountOfParticipants = 17,
                            Name = "Body Pump",
                            StartDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/bodypump/600/400",
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            CurrentParticipants = 8,
                            MaxAmountOfParticipants = 14,
                            Name = "Functional Training",
                            StartDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/functional/600/400",
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            CurrentParticipants = 6,
                            MaxAmountOfParticipants = 12,
                            Name = "Stretching",
                            StartDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/stretching/600/400",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CurrentParticipants = 18,
                            MaxAmountOfParticipants = 20,
                            Name = "Bootcamp",
                            StartDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/bootcamp/600/400",
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            CurrentParticipants = 9,
                            MaxAmountOfParticipants = 15,
                            Name = "Abs Workout",
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/absworkout/600/400",
                            UserId = 5
                        },
                        new
                        {
                            Id = 16,
                            CurrentParticipants = 5,
                            MaxAmountOfParticipants = 10,
                            Name = "Powerlifting",
                            StartDate = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/powerlifting/600/400",
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            CurrentParticipants = 14,
                            MaxAmountOfParticipants = 20,
                            Name = "Zumba",
                            StartDate = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/zumba/600/400",
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            CurrentParticipants = 12,
                            MaxAmountOfParticipants = 18,
                            Name = "Aerobics",
                            StartDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/aerobics/600/400",
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            CurrentParticipants = 11,
                            MaxAmountOfParticipants = 16,
                            Name = "Circuit Training",
                            StartDate = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/circuit/600/400",
                            UserId = 5
                        },
                        new
                        {
                            Id = 20,
                            CurrentParticipants = 10,
                            MaxAmountOfParticipants = 15,
                            Name = "Core Workout",
                            StartDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/core/600/400",
                            UserId = 6
                        },
                        new
                        {
                            Id = 21,
                            CurrentParticipants = 11,
                            MaxAmountOfParticipants = 15,
                            Name = "HIIT (Feb)",
                            StartDate = new DateTime(2026, 2, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/hiitfeb/600/400",
                            UserId = 3
                        },
                        new
                        {
                            Id = 22,
                            CurrentParticipants = 9,
                            MaxAmountOfParticipants = 12,
                            Name = "Yoga Flow (Feb)",
                            StartDate = new DateTime(2026, 2, 14, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/yogafeb/600/400",
                            UserId = 4
                        },
                        new
                        {
                            Id = 23,
                            CurrentParticipants = 13,
                            MaxAmountOfParticipants = 16,
                            Name = "Strength Training (Feb)",
                            StartDate = new DateTime(2026, 2, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/strengthfeb/600/400",
                            UserId = 5
                        },
                        new
                        {
                            Id = 24,
                            CurrentParticipants = 10,
                            MaxAmountOfParticipants = 14,
                            Name = "Boxing (Feb)",
                            StartDate = new DateTime(2026, 2, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingImage = "https://picsum.photos/seed/boxingfeb/600/400",
                            UserId = 6
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRadnik")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTrener")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUser")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "healthcaretest190@gmail.com",
                            FirstName = "Tarik",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Malic",
                            PasswordHash = "a/ltJ7B7vtcMZhCIzkgBJXCATnneMEFEc3Hgx94v0nGcbFkUX2pthowUrhxC1XSO2U+eLfnj7LFU1IUgNYffug==",
                            PasswordSalt = "CcnZ27SnBRmidH0pkSukCGrXgDt5//O1hzk6YfwhxQiudnQphUnNz60OQo3ADwZfJnYEG1P4m73ypqwkmywecN4sxYh5p0eAtRsYN6ykzF4xiPz7zr7o+KGLmTRIpvSl97idCk57a7HXfjme/CAWfkTidyafWQLS6awRMuTzYxY=",
                            PhoneNumber = "061111111",
                            Username = "tare45"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1994, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amir@example.com",
                            FirstName = "Amir",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Ibrahimovic",
                            PasswordHash = "a/ltJ7B7vtcMZhCIzkgBJXCATnneMEFEc3Hgx94v0nGcbFkUX2pthowUrhxC1XSO2U+eLfnj7LFU1IUgNYffug==",
                            PasswordSalt = "CcnZ27SnBRmidH0pkSukCGrXgDt5//O1hzk6YfwhxQiudnQphUnNz60OQo3ADwZfJnYEG1P4m73ypqwkmywecN4sxYh5p0eAtRsYN6ykzF4xiPz7zr7o+KGLmTRIpvSl97idCk57a7HXfjme/CAWfkTidyafWQLS6awRMuTzYxY=",
                            PhoneNumber = "061111112",
                            Username = "amir56"
                        },
                        new
                        {
                            Id = 3,
                            AboutMe = "Licencirani fitness trener sa 5 godina iskustva u radu sa klijentima svih uzrasta.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko@example.com",
                            FirstName = "Marko",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Markovic",
                            PasswordHash = "NqfMnfO/TvQrSWt7BTlSlGIXiuXbIQFrDD14EHu0l1N/uh6jAtpp/DdUVurizbfI02Z5BS2bhZFVBIwfPwhzXg==",
                            PasswordSalt = "1bHWJrU96ikBB1lg3+s0+b1oRGQYOCBqkXEim2ax58Lz6CcbEVe1/dKZD+X3eNeHR01nhjsiaXE8MwdjW7vh2tcNxF613HLKBGSKjYgvU5wU/50y0iz/1fUuovvPfk1ostCfmyrNAjtQdJRPkzCKVNQU71WY+kWvZlDtySNuQKc=",
                            PhoneNumber = "061111113",
                            Username = "marko78"
                        },
                        new
                        {
                            Id = 4,
                            AboutMe = "Specijalizovan za kondicionu pripremu i izgradnju mišićne mase.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1989, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan@example.com",
                            FirstName = "Ivan",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Ivic",
                            PasswordHash = "NqfMnfO/TvQrSWt7BTlSlGIXiuXbIQFrDD14EHu0l1N/uh6jAtpp/DdUVurizbfI02Z5BS2bhZFVBIwfPwhzXg==",
                            PasswordSalt = "1bHWJrU96ikBB1lg3+s0+b1oRGQYOCBqkXEim2ax58Lz6CcbEVe1/dKZD+X3eNeHR01nhjsiaXE8MwdjW7vh2tcNxF613HLKBGSKjYgvU5wU/50y0iz/1fUuovvPfk1ostCfmyrNAjtQdJRPkzCKVNQU71WY+kWvZlDtySNuQKc=",
                            PhoneNumber = "061111114",
                            Username = "ivan11"
                        },
                        new
                        {
                            Id = 5,
                            AboutMe = "Stručnjak za funkcionalne treninge i planove ishrane.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petar@example.com",
                            FirstName = "Petar",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Petrovic",
                            PasswordHash = "NqfMnfO/TvQrSWt7BTlSlGIXiuXbIQFrDD14EHu0l1N/uh6jAtpp/DdUVurizbfI02Z5BS2bhZFVBIwfPwhzXg==",
                            PasswordSalt = "1bHWJrU96ikBB1lg3+s0+b1oRGQYOCBqkXEim2ax58Lz6CcbEVe1/dKZD+X3eNeHR01nhjsiaXE8MwdjW7vh2tcNxF613HLKBGSKjYgvU5wU/50y0iz/1fUuovvPfk1ostCfmyrNAjtQdJRPkzCKVNQU71WY+kWvZlDtySNuQKc=",
                            PhoneNumber = "061111115",
                            Username = "petar21"
                        },
                        new
                        {
                            Id = 6,
                            AboutMe = "Posvećen radu sa početnicima i personalizovanim fitness programima.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "luka@example.com",
                            FirstName = "Luka",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Lukic",
                            PasswordHash = "NqfMnfO/TvQrSWt7BTlSlGIXiuXbIQFrDD14EHu0l1N/uh6jAtpp/DdUVurizbfI02Z5BS2bhZFVBIwfPwhzXg==",
                            PasswordSalt = "1bHWJrU96ikBB1lg3+s0+b1oRGQYOCBqkXEim2ax58Lz6CcbEVe1/dKZD+X3eNeHR01nhjsiaXE8MwdjW7vh2tcNxF613HLKBGSKjYgvU5wU/50y0iz/1fUuovvPfk1ostCfmyrNAjtQdJRPkzCKVNQU71WY+kWvZlDtySNuQKc=",
                            PhoneNumber = "061111116",
                            Username = "luka34"
                        },
                        new
                        {
                            Id = 7,
                            AboutMe = "Zadužen za organizaciju termina i podršku članovima teretane.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1996, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nedim@example.com",
                            FirstName = "Nedim",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Nedimovic",
                            PasswordHash = "NeLI1bzsBtEfLvrvyBiyoAwp/cwe0wNZqTWIfEb4+kzqtW4/JUXtrZdDuC2SjAk1MiTlBj0DoE9Iv9PviAZh+g==",
                            PasswordSalt = "lWL//ugb+8T/rG16xcttUfa8fLd/OpWJRQYYBxl7tGSWGNlu8oyKOTuWw/9QD+nMt9Sq5VmMirqgJXCVdmI/DX0chz0Qpd+Piz5+yPGabBfBrEGAe0ONQMLl0Z0N1Lafj9MCr0OSsdw2kGwM0OSoSDGqsL4nzDi6GbKuGdaBRBc=",
                            PhoneNumber = "061111117",
                            Username = "nedim89"
                        },
                        new
                        {
                            Id = 8,
                            AboutMe = "Brine o administraciji i svakodnevnom radu fitness centra.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1997, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amela@example.com",
                            FirstName = "Amela",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Amelovic",
                            PasswordHash = "NeLI1bzsBtEfLvrvyBiyoAwp/cwe0wNZqTWIfEb4+kzqtW4/JUXtrZdDuC2SjAk1MiTlBj0DoE9Iv9PviAZh+g==",
                            PasswordSalt = "lWL//ugb+8T/rG16xcttUfa8fLd/OpWJRQYYBxl7tGSWGNlu8oyKOTuWw/9QD+nMt9Sq5VmMirqgJXCVdmI/DX0chz0Qpd+Piz5+yPGabBfBrEGAe0ONQMLl0Z0N1Lafj9MCr0OSsdw2kGwM0OSoSDGqsL4nzDi6GbKuGdaBRBc=",
                            PhoneNumber = "061111118",
                            Username = "amela900"
                        },
                        new
                        {
                            Id = 9,
                            AboutMe = "Odgovoran za korisničku podršku i prijem novih članova.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tarik@example.com",
                            FirstName = "Tarik",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Tarikovic",
                            PasswordHash = "NeLI1bzsBtEfLvrvyBiyoAwp/cwe0wNZqTWIfEb4+kzqtW4/JUXtrZdDuC2SjAk1MiTlBj0DoE9Iv9PviAZh+g==",
                            PasswordSalt = "lWL//ugb+8T/rG16xcttUfa8fLd/OpWJRQYYBxl7tGSWGNlu8oyKOTuWw/9QD+nMt9Sq5VmMirqgJXCVdmI/DX0chz0Qpd+Piz5+yPGabBfBrEGAe0ONQMLl0Z0N1Lafj9MCr0OSsdw2kGwM0OSoSDGqsL4nzDi6GbKuGdaBRBc=",
                            PhoneNumber = "061111119",
                            Username = "tarik345"
                        },
                        new
                        {
                            Id = 10,
                            AboutMe = "Koordinira raspored treninga i komunikaciju sa trenerima.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1998, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emina@example.com",
                            FirstName = "Emina",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Eminovic",
                            PasswordHash = "NeLI1bzsBtEfLvrvyBiyoAwp/cwe0wNZqTWIfEb4+kzqtW4/JUXtrZdDuC2SjAk1MiTlBj0DoE9Iv9PviAZh+g==",
                            PasswordSalt = "lWL//ugb+8T/rG16xcttUfa8fLd/OpWJRQYYBxl7tGSWGNlu8oyKOTuWw/9QD+nMt9Sq5VmMirqgJXCVdmI/DX0chz0Qpd+Piz5+yPGabBfBrEGAe0ONQMLl0Z0N1Lafj9MCr0OSsdw2kGwM0OSoSDGqsL4nzDi6GbKuGdaBRBc=",
                            PhoneNumber = "061111120",
                            Username = "emina112"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2000, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "haris1@example.com",
                            FirstName = "Haris",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Hasic",
                            PasswordHash = "MXdbK5opJla0Z/g5ooMWC0q1YjuHdHgRJ2gz/1B39WFEN9Vz12gLMp+f1d/4+eLCZpgOdpilzDqOiYB/FLrLoQ==",
                            PasswordSalt = "QizuJj4FZxWkWzcb9akyUsJir5SJUljCGIyiWZg1SqBXrIBo1mgL13jZ3sQsNsiLsNh8HPrH1+zH6JPXBhgDb5gY95Dyq+MrpgxKZXZ+65Q2CqgcGfMta+gmkwFU++y/xgIA9tjItMZqAmhWFPzodD6DROnApc/8txerKBLTsqY=",
                            PhoneNumber = "061111121",
                            Username = "haris1"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1999, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "denis2@example.com",
                            FirstName = "Denis",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Denisovic",
                            PasswordHash = "MXdbK5opJla0Z/g5ooMWC0q1YjuHdHgRJ2gz/1B39WFEN9Vz12gLMp+f1d/4+eLCZpgOdpilzDqOiYB/FLrLoQ==",
                            PasswordSalt = "QizuJj4FZxWkWzcb9akyUsJir5SJUljCGIyiWZg1SqBXrIBo1mgL13jZ3sQsNsiLsNh8HPrH1+zH6JPXBhgDb5gY95Dyq+MrpgxKZXZ+65Q2CqgcGfMta+gmkwFU++y/xgIA9tjItMZqAmhWFPzodD6DROnApc/8txerKBLTsqY=",
                            PhoneNumber = "061111122",
                            Username = "denis2"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alen3@example.com",
                            FirstName = "Alen",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Alenovic",
                            PasswordHash = "MXdbK5opJla0Z/g5ooMWC0q1YjuHdHgRJ2gz/1B39WFEN9Vz12gLMp+f1d/4+eLCZpgOdpilzDqOiYB/FLrLoQ==",
                            PasswordSalt = "QizuJj4FZxWkWzcb9akyUsJir5SJUljCGIyiWZg1SqBXrIBo1mgL13jZ3sQsNsiLsNh8HPrH1+zH6JPXBhgDb5gY95Dyq+MrpgxKZXZ+65Q2CqgcGfMta+gmkwFU++y/xgIA9tjItMZqAmhWFPzodD6DROnApc/8txerKBLTsqY=",
                            PhoneNumber = "061111123",
                            Username = "alen3"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1998, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kenan4@example.com",
                            FirstName = "Kenan",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Kenanovic",
                            PasswordHash = "MXdbK5opJla0Z/g5ooMWC0q1YjuHdHgRJ2gz/1B39WFEN9Vz12gLMp+f1d/4+eLCZpgOdpilzDqOiYB/FLrLoQ==",
                            PasswordSalt = "QizuJj4FZxWkWzcb9akyUsJir5SJUljCGIyiWZg1SqBXrIBo1mgL13jZ3sQsNsiLsNh8HPrH1+zH6JPXBhgDb5gY95Dyq+MrpgxKZXZ+65Q2CqgcGfMta+gmkwFU++y/xgIA9tjItMZqAmhWFPzodD6DROnApc/8txerKBLTsqY=",
                            PhoneNumber = "061111124",
                            Username = "kenan4"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1997, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jasmin5@example.com",
                            FirstName = "Jasmin",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Jasminovic",
                            PasswordHash = "MXdbK5opJla0Z/g5ooMWC0q1YjuHdHgRJ2gz/1B39WFEN9Vz12gLMp+f1d/4+eLCZpgOdpilzDqOiYB/FLrLoQ==",
                            PasswordSalt = "QizuJj4FZxWkWzcb9akyUsJir5SJUljCGIyiWZg1SqBXrIBo1mgL13jZ3sQsNsiLsNh8HPrH1+zH6JPXBhgDb5gY95Dyq+MrpgxKZXZ+65Q2CqgcGfMta+gmkwFU++y/xgIA9tjItMZqAmhWFPzodD6DROnApc/8txerKBLTsqY=",
                            PhoneNumber = "061111125",
                            Username = "jasmin5"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lejla6@example.com",
                            FirstName = "Lejla",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Lejlovic",
                            PasswordHash = "MXdbK5opJla0Z/g5ooMWC0q1YjuHdHgRJ2gz/1B39WFEN9Vz12gLMp+f1d/4+eLCZpgOdpilzDqOiYB/FLrLoQ==",
                            PasswordSalt = "QizuJj4FZxWkWzcb9akyUsJir5SJUljCGIyiWZg1SqBXrIBo1mgL13jZ3sQsNsiLsNh8HPrH1+zH6JPXBhgDb5gY95Dyq+MrpgxKZXZ+65Q2CqgcGfMta+gmkwFU++y/xgIA9tjItMZqAmhWFPzodD6DROnApc/8txerKBLTsqY=",
                            PhoneNumber = "061111126",
                            Username = "lejla6"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara7@example.com",
                            FirstName = "Sara",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Saric",
                            PasswordHash = "MXdbK5opJla0Z/g5ooMWC0q1YjuHdHgRJ2gz/1B39WFEN9Vz12gLMp+f1d/4+eLCZpgOdpilzDqOiYB/FLrLoQ==",
                            PasswordSalt = "QizuJj4FZxWkWzcb9akyUsJir5SJUljCGIyiWZg1SqBXrIBo1mgL13jZ3sQsNsiLsNh8HPrH1+zH6JPXBhgDb5gY95Dyq+MrpgxKZXZ+65Q2CqgcGfMta+gmkwFU++y/xgIA9tjItMZqAmhWFPzodD6DROnApc/8txerKBLTsqY=",
                            PhoneNumber = "061111127",
                            Username = "sara7"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1999, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amina8@example.com",
                            FirstName = "Amina",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Aminovic",
                            PasswordHash = "MXdbK5opJla0Z/g5ooMWC0q1YjuHdHgRJ2gz/1B39WFEN9Vz12gLMp+f1d/4+eLCZpgOdpilzDqOiYB/FLrLoQ==",
                            PasswordSalt = "QizuJj4FZxWkWzcb9akyUsJir5SJUljCGIyiWZg1SqBXrIBo1mgL13jZ3sQsNsiLsNh8HPrH1+zH6JPXBhgDb5gY95Dyq+MrpgxKZXZ+65Q2CqgcGfMta+gmkwFU++y/xgIA9tjItMZqAmhWFPzodD6DROnApc/8txerKBLTsqY=",
                            PhoneNumber = "061111128",
                            Username = "amina8"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1998, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emir9@example.com",
                            FirstName = "Emir",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Emirovic",
                            PasswordHash = "MXdbK5opJla0Z/g5ooMWC0q1YjuHdHgRJ2gz/1B39WFEN9Vz12gLMp+f1d/4+eLCZpgOdpilzDqOiYB/FLrLoQ==",
                            PasswordSalt = "QizuJj4FZxWkWzcb9akyUsJir5SJUljCGIyiWZg1SqBXrIBo1mgL13jZ3sQsNsiLsNh8HPrH1+zH6JPXBhgDb5gY95Dyq+MrpgxKZXZ+65Q2CqgcGfMta+gmkwFU++y/xgIA9tjItMZqAmhWFPzodD6DROnApc/8txerKBLTsqY=",
                            PhoneNumber = "061111129",
                            Username = "emir9"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1997, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nermin10@example.com",
                            FirstName = "Nermin",
                            IsActive = true,
                            IsUser = true,
                            LastName = "Nerminovic",
                            PasswordHash = "MXdbK5opJla0Z/g5ooMWC0q1YjuHdHgRJ2gz/1B39WFEN9Vz12gLMp+f1d/4+eLCZpgOdpilzDqOiYB/FLrLoQ==",
                            PasswordSalt = "QizuJj4FZxWkWzcb9akyUsJir5SJUljCGIyiWZg1SqBXrIBo1mgL13jZ3sQsNsiLsNh8HPrH1+zH6JPXBhgDb5gY95Dyq+MrpgxKZXZ+65Q2CqgcGfMta+gmkwFU++y/xgIA9tjItMZqAmhWFPzodD6DROnApc/8txerKBLTsqY=",
                            PhoneNumber = "061111130",
                            Username = "nermin10"
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8036),
                            RoleId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8518),
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8520),
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8520),
                            RoleId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8521),
                            RoleId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8522),
                            RoleId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8523),
                            RoleId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8524),
                            RoleId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8525),
                            RoleId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8551),
                            RoleId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8552),
                            RoleId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8553),
                            RoleId = 1,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8586),
                            RoleId = 1,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8587),
                            RoleId = 1,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8588),
                            RoleId = 1,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8589),
                            RoleId = 1,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8590),
                            RoleId = 1,
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8591),
                            RoleId = 1,
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8592),
                            RoleId = 1,
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            DateAssigned = new DateTime(2026, 3, 3, 3, 57, 46, 413, DateTimeKind.Utc).AddTicks(8593),
                            RoleId = 1,
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.WorkerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTaskDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExparationTaskDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkerTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTaskDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Izvršiti dnevnu provjeru sprava u sali 1.",
                            ExparationTaskDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = false,
                            Name = "Provjera opreme",
                            UserId = 7
                        },
                        new
                        {
                            Id = 2,
                            CreatedTaskDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Detaljno čišćenje muške svlačionice.",
                            ExparationTaskDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = true,
                            Name = "Čišćenje svlačionice",
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            CreatedTaskDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Provjeriti stanje proteinskih napitaka.",
                            ExparationTaskDate = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = false,
                            Name = "Inventura šanka",
                            UserId = 8
                        },
                        new
                        {
                            Id = 4,
                            CreatedTaskDate = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Rasporediti termine za nove članove.",
                            ExparationTaskDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = false,
                            Name = "Organizacija termina",
                            UserId = 8
                        },
                        new
                        {
                            Id = 5,
                            CreatedTaskDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Provjeriti članarine koje ističu ove sedmice.",
                            ExparationTaskDate = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = true,
                            Name = "Ažuriranje članova",
                            UserId = 9
                        },
                        new
                        {
                            Id = 6,
                            CreatedTaskDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Pripremiti salu za večernji grupni trening.",
                            ExparationTaskDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = false,
                            Name = "Priprema sale",
                            UserId = 9
                        },
                        new
                        {
                            Id = 7,
                            CreatedTaskDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Objaviti promociju na društvenim mrežama.",
                            ExparationTaskDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = false,
                            Name = "Marketing objava",
                            UserId = 10
                        },
                        new
                        {
                            Id = 8,
                            CreatedTaskDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Provjeriti rezervacije za vikend termine.",
                            ExparationTaskDate = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinished = true,
                            Name = "Pregled rezervacija",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPoint", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPointHistory", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Member", b =>
                {
                    b.HasOne("Gymify.Services.Database.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Notification", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Payment", b =>
                {
                    b.HasOne("Gymify.Services.Database.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Reservation", b =>
                {
                    b.HasOne("Gymify.Services.Database.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Review", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Training", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.UserRole", b =>
                {
                    b.HasOne("Gymify.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.WorkerTask", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Gymify.Services.Database.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
