// <auto-generated />
using System;
using Gymify.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gymify.Services.Migrations
{
    [DbContext(typeof(GymifyDbContext))]
    partial class GymifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoyaltyPoints");
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPointHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountPointsParticipation")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoyaltyPointHistories");
                });

            modelBuilder.Entity("Gymify.Services.Database.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Gymify.Services.Database.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detaisl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Gymify.Services.Database.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Gymify.Services.Database.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Gymify.Services.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StarNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Gymify.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 759, DateTimeKind.Utc).AddTicks(46),
                            Description = "",
                            IsActive = true,
                            Name = "Korisnik"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 759, DateTimeKind.Utc).AddTicks(500),
                            Description = "",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 759, DateTimeKind.Utc).AddTicks(502),
                            Description = "",
                            IsActive = true,
                            Name = "Trener"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 759, DateTimeKind.Utc).AddTicks(503),
                            Description = "",
                            IsActive = true,
                            Name = "Radnik"
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.SpecialOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValueOfLoyaltyPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpecialOffers");
                });

            modelBuilder.Entity("Gymify.Services.Database.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("int");

                    b.Property<int>("MaxAmountOfParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("Gymify.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRadnik")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTrener")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUser")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(4473),
                            Email = "ajdin@example.com",
                            FirstName = "Tarik",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Malic",
                            PasswordHash = "Zr1yNL0PufElmoWUKiywJXZiR9ph00sz67ucqetSNOqEGdxODG4plmzu/jquyPnS+9BxZIb3y9h5EaQQJUVOPw==",
                            PasswordSalt = "i3sFkRAERrTgIDIz5MbXP6B5cyYSqTD7DOpOhq1zurYgCJn3BjA1SpE/a9Qv1huFaH57SteTbaA2uId7c4/o7+n5VDXnEb/Y7I/am9LrKOQGeOSdrSg/cgUBf/L6Mw8wlWWiSij7iMUw5zW4zExKzwYLpi2Y28x/0lJotdYvfSA=",
                            Username = "tare45"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(4916),
                            Email = "amir@example.com",
                            FirstName = "Amir",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Ibrahimovic",
                            PasswordHash = "Zr1yNL0PufElmoWUKiywJXZiR9ph00sz67ucqetSNOqEGdxODG4plmzu/jquyPnS+9BxZIb3y9h5EaQQJUVOPw==",
                            PasswordSalt = "i3sFkRAERrTgIDIz5MbXP6B5cyYSqTD7DOpOhq1zurYgCJn3BjA1SpE/a9Qv1huFaH57SteTbaA2uId7c4/o7+n5VDXnEb/Y7I/am9LrKOQGeOSdrSg/cgUBf/L6Mw8wlWWiSij7iMUw5zW4zExKzwYLpi2Y28x/0lJotdYvfSA=",
                            Username = "amir56"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(5052),
                            Email = "marko@example.com",
                            FirstName = "Marko",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Markovic",
                            PasswordHash = "rf+iRBC3+Or3QUIDpDUuoHiS88jzJ5YEpvK/eiNLPouKobVrWctIAYyzIUoL0++XIDsaqFXuSUgGtv5K20MiPg==",
                            PasswordSalt = "/P1/X5G5cYEYmWouZSL7au0ZJ9pvffTAes5jpZK1ShVOUu1WJNxiZGIz9mV/zfAhLU2HDrxhxlRdU5ISmEBcu5GC7/sUiq3+fGzZRrxaBVNO4cFpNJND+XA/k5NHykxwYCN7PqX3+a2/O3sj4Vg7ef9G786TCT5vVRqJsoCC70w=",
                            Username = "marko78"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(5056),
                            Email = "ivan@example.com",
                            FirstName = "Ivan",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Ivic",
                            PasswordHash = "rf+iRBC3+Or3QUIDpDUuoHiS88jzJ5YEpvK/eiNLPouKobVrWctIAYyzIUoL0++XIDsaqFXuSUgGtv5K20MiPg==",
                            PasswordSalt = "/P1/X5G5cYEYmWouZSL7au0ZJ9pvffTAes5jpZK1ShVOUu1WJNxiZGIz9mV/zfAhLU2HDrxhxlRdU5ISmEBcu5GC7/sUiq3+fGzZRrxaBVNO4cFpNJND+XA/k5NHykxwYCN7PqX3+a2/O3sj4Vg7ef9G786TCT5vVRqJsoCC70w=",
                            Username = "ivan11"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(5058),
                            Email = "petar@example.com",
                            FirstName = "Petar",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Petrovic",
                            PasswordHash = "rf+iRBC3+Or3QUIDpDUuoHiS88jzJ5YEpvK/eiNLPouKobVrWctIAYyzIUoL0++XIDsaqFXuSUgGtv5K20MiPg==",
                            PasswordSalt = "/P1/X5G5cYEYmWouZSL7au0ZJ9pvffTAes5jpZK1ShVOUu1WJNxiZGIz9mV/zfAhLU2HDrxhxlRdU5ISmEBcu5GC7/sUiq3+fGzZRrxaBVNO4cFpNJND+XA/k5NHykxwYCN7PqX3+a2/O3sj4Vg7ef9G786TCT5vVRqJsoCC70w=",
                            Username = "petar21"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(5060),
                            Email = "luka@example.com",
                            FirstName = "Luka",
                            IsActive = true,
                            IsTrener = true,
                            LastName = "Lukic",
                            PasswordHash = "rf+iRBC3+Or3QUIDpDUuoHiS88jzJ5YEpvK/eiNLPouKobVrWctIAYyzIUoL0++XIDsaqFXuSUgGtv5K20MiPg==",
                            PasswordSalt = "/P1/X5G5cYEYmWouZSL7au0ZJ9pvffTAes5jpZK1ShVOUu1WJNxiZGIz9mV/zfAhLU2HDrxhxlRdU5ISmEBcu5GC7/sUiq3+fGzZRrxaBVNO4cFpNJND+XA/k5NHykxwYCN7PqX3+a2/O3sj4Vg7ef9G786TCT5vVRqJsoCC70w=",
                            Username = "luka34"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(5194),
                            Email = "nedim@example.com",
                            FirstName = "Nedim",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Nedimovic",
                            PasswordHash = "WFiLOJuHLZNlNwIn/7JPsZRWwSbX9d4WOPZfrudDIMCzL+yrSoIUGfflS6Nb6O159An87pMC/7xgTXcvC+bXug==",
                            PasswordSalt = "xa7tCyzbFr4FJ8QeeJa47dDbRHC2u+F57iwgrlipKAH/5Y9huunkmoy2yQdjxhoDSEDfgp2dbyU91v8/lPmtL1nDy2OpOMQc+86Z3TfatN7J6szK0qSLYb/VjlG3tKaSrVN6cpmBdF5D777aVOyBlf+D+vxBEpeGXUZfOG4jYUM=",
                            Username = "nedim89"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(5197),
                            Email = "amela@example.com",
                            FirstName = "Amela",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Amelovic",
                            PasswordHash = "WFiLOJuHLZNlNwIn/7JPsZRWwSbX9d4WOPZfrudDIMCzL+yrSoIUGfflS6Nb6O159An87pMC/7xgTXcvC+bXug==",
                            PasswordSalt = "xa7tCyzbFr4FJ8QeeJa47dDbRHC2u+F57iwgrlipKAH/5Y9huunkmoy2yQdjxhoDSEDfgp2dbyU91v8/lPmtL1nDy2OpOMQc+86Z3TfatN7J6szK0qSLYb/VjlG3tKaSrVN6cpmBdF5D777aVOyBlf+D+vxBEpeGXUZfOG4jYUM=",
                            Username = "amela900"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(5199),
                            Email = "tarik@example.com",
                            FirstName = "Tarik",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Tarikovic",
                            PasswordHash = "WFiLOJuHLZNlNwIn/7JPsZRWwSbX9d4WOPZfrudDIMCzL+yrSoIUGfflS6Nb6O159An87pMC/7xgTXcvC+bXug==",
                            PasswordSalt = "xa7tCyzbFr4FJ8QeeJa47dDbRHC2u+F57iwgrlipKAH/5Y9huunkmoy2yQdjxhoDSEDfgp2dbyU91v8/lPmtL1nDy2OpOMQc+86Z3TfatN7J6szK0qSLYb/VjlG3tKaSrVN6cpmBdF5D777aVOyBlf+D+vxBEpeGXUZfOG4jYUM=",
                            Username = "tarik345"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(5201),
                            Email = "emina@example.com",
                            FirstName = "Emina",
                            IsActive = true,
                            IsRadnik = true,
                            LastName = "Eminovic",
                            PasswordHash = "WFiLOJuHLZNlNwIn/7JPsZRWwSbX9d4WOPZfrudDIMCzL+yrSoIUGfflS6Nb6O159An87pMC/7xgTXcvC+bXug==",
                            PasswordSalt = "xa7tCyzbFr4FJ8QeeJa47dDbRHC2u+F57iwgrlipKAH/5Y9huunkmoy2yQdjxhoDSEDfgp2dbyU91v8/lPmtL1nDy2OpOMQc+86Z3TfatN7J6szK0qSLYb/VjlG3tKaSrVN6cpmBdF5D777aVOyBlf+D+vxBEpeGXUZfOG4jYUM=",
                            Username = "emina112"
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAssigned = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(5877),
                            RoleId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAssigned = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(6337),
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAssigned = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(6338),
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAssigned = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(6339),
                            RoleId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateAssigned = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(6340),
                            RoleId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(6341),
                            RoleId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(6342),
                            RoleId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateAssigned = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(6342),
                            RoleId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            DateAssigned = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(6381),
                            RoleId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            DateAssigned = new DateTime(2026, 2, 12, 21, 22, 35, 764, DateTimeKind.Utc).AddTicks(6382),
                            RoleId = 4,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Gymify.Services.Database.WorkerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTaskDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExparationTaskDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkerTasks");
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPoint", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.LoyaltyPointHistory", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Member", b =>
                {
                    b.HasOne("Gymify.Services.Database.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Payment", b =>
                {
                    b.HasOne("Gymify.Services.Database.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Reservation", b =>
                {
                    b.HasOne("Gymify.Services.Database.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Review", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Training", b =>
                {
                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.UserRole", b =>
                {
                    b.HasOne("Gymify.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gymify.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Gymify.Services.Database.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
